[build]
  command = "rm -rf .cache build && npm run build"
  publish = "build/client"

[functions]
  directory = "build/server"

[build.environment]
  NODE_VERSION = "18"
  # Force fresh builds by clearing cache
  NETLIFY_CACHE_INVALIDATOR = "2025-10-03"