[build]
  command = "rm -rf .cache build && npm run build"
  publish = "build/client"

[functions]
  directory = "build/server"
  node_bundler = "esbuild"

[[functions]]
  path = "/*"
  node_bundler = "esbuild"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM https://admin.shopify.com/"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_CACHE_INVALIDATOR = "2025-10-03-v3"

# Critical: Serve static assets BEFORE routing to function
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200