# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "19b92a0c7d4e217c2220271d82babe19"
name = "newP"
handle = "newp"
application_url = "https://background-obesity-format-severe.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_script_tags"

[auth]
redirect_urls = ["https://background-obesity-format-severe.trycloudflare.com/auth/callback", "https://background-obesity-format-severe.trycloudflare.com/auth/shopify/callback", "https://background-obesity-format-severe.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
