# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "19b92a0c7d4e217c2220271d82babe19"
name = "newP"
handle = "newp"
application_url = "https://new-p-shopify.netlify.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_script_tags"

[auth]
redirect_urls = ["https://new-p-shopify.netlify.app/auth/callback", "https://new-p-shopify.netlify.app/auth/shopify/callback", "https://new-p-shopify.netlify.app/api/auth/callback"]

[pos]
embedded = false
