# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "19b92a0c7d4e217c2220271d82babe19"
name = "newP"
handle = "newp"
application_url = "https://tiles-us-joining-terrain.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/products/create"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/products/delete"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_script_tags"

[auth]
redirect_urls = ["https://tiles-us-joining-terrain.trycloudflare.com/auth/callback", "https://tiles-us-joining-terrain.trycloudflare.com/auth/shopify/callback", "https://tiles-us-joining-terrain.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
