# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "19b92a0c7d4e217c2220271d82babe19"
name = "newP"
application_url = "https://playlist-jar-confirmed-consult.trycloudflare.com"
embedded = true
handle = "newp"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/products/create"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products/update"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/products/delete"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "shop/update" ]
  uri = "/webhooks/shop/update"

  [[webhooks.subscriptions]]
  topics = [ "bulk_operations/finish" ]
  uri = "/webhooks/bulk_operations/finish"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://playlist-jar-confirmed-consult.trycloudflare.com/auth/callback",
  "https://playlist-jar-confirmed-consult.trycloudflare.com/auth/shopify/callback",
  "https://playlist-jar-confirmed-consult.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
