name = "visual-search-theme"
type = "theme"

[[app_blocks]]
  name = "Float Image Search"
  target = "body"
  icon = "visual-search-logo.svg"

[[app_blocks]]
  name = "VS Icon_pankaj"
  target = "section"
  icon = "visual-search-logo.svg"

